application:
  title: rentalmanagement
  version: 0.0.1-SNAPSHOT

server:
  servlet:
    context-path: /rental
  port: 8080

spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: d203c19959ce72
    password: cd279a4d5d2862
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/rental_management_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
