application:
  title: rentalmanagement
  version: 0.0.1-SNAPSHOT

server:
  servlet:
    context-path: /rental
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rental_management_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      springframework: trace